services:
  mysql:
    image: mysql:8
    container_name: mysql-ecommerce
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_network

volumes:
  mysql_data:
    driver: local

networks:
  ecommerce_network:
